backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "/src/img"
public_folder: "/_site/asset"
local_backend: true

collections:
  - name: "posts"
    label: "Post"
    folder: "/src/post/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Writer", name: "writer", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }